openapi: 3.0.1
info:
  title: HelloWorld
  description: API Definition of HelloWorld
  version: 1.0.0
servers:
  - url: 'http://localhost:8290/hello'
security:
  - default: []
paths:
  /message:
    get:
      responses:
        default:
          description: Default response
      security:
        - default: []
      x-throttling-tier: Unlimited
      x-auth-type: Application & Application User
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://test.com'
          scopes: {}
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
    - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
    - authorization
    - Access-Control-Allow-Origin
    - Content-Type
    - SOAPAction
    - apikey
    - Internal-Key
  accessControlAllowMethods:
    - GET
    - PUT
    - POST
    - DELETE
    - PATCH
    - OPTIONS
x-wso2-production-endpoints:
  urls:
    - 'http://localhost:8290/hello'
  type: http
x-wso2-sandbox-endpoints:
  urls:
    - 'http://localhost:8290/hello'
  type: http
x-wso2-basePath: /helloworld/1.0.0
x-wso2-transports:
  - http
  - https
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
